### PR TITLE
Apply Apache v2.0 license

### PR DESCRIPTION
**Pull request by mancabizjak**
This commit adds LICENSE and AUTHORS files and adds the license header to all original source files.

### CODE REVIEW

**Comment by mancabizjak** [comment]
@miha-plesko I think it's a matter of preference, it is certainly not required by the license (the only required stuff goes in LICENSE or NOTICE). But it is quite common. I was checking two other repos, go-grpc and one of go-grpc-ecosystem repos, which are both licensed under Apache v2.0 and both had the AUTHORS file.

But if the copyright notice in the comments of source files clearly states the author, then you should be okay. 

If @miha-stopar prefers putting the company name instead of "Emmy authors" in license header, I'm okay with it and will change :+1:

**Comment by miha-stopar** [comment]
@mancabizjak I think XLAB is more appropriate.

**Comment by mancabizjak** [comment]
Allright then, I'll remove AUTHORS and modify headers with the next commit.

**Comment by mancabizjak** [comment]
Okay, it is done. I think we can merge @miha-stopar?

**Pull request merged**
